### ISSUE TITLE
Rules Regex is wrong type (string)

### ISSUE THREAD

**Issue by cuongbuoi** [zhorton34/vuejs-validators#27]
![image](https://user-images.githubusercontent.com/23218035/120992916-41138500-c7ad-11eb-84c6-634c0988a6bb.png)

typeof parameters[0] is string, must object

to fix this issue:
regex: ({ value, parameters }) => new RegExp(parameters[0]).test(value),

**Comment by zhorton34** [comment]
@cuongbuoi Any chance you're able to throw that change in and a quick pr? Haven't touched the code in a minute and in the middle of an intense interview process at one of the FAANG companies so won't have time for at least a few weeks.
